import type { TemplateCatalogItem, TemplateSectionDefinition } from '@/lib/types';

function section(
  key: string,
  title: string,
  guidance: string,
  maps_to: TemplateSectionDefinition['maps_to'] = 'document',
  required = true
): TemplateSectionDefinition {
  return { key, title, guidance, required, maps_to };
}

function makeTemplate(template: TemplateCatalogItem): TemplateCatalogItem {
  return template;
}

export const DEFAULT_TEMPLATE_KEY = 'soap-note';

export const TEMPLATE_CATALOG: TemplateCatalogItem[] = [
  makeTemplate({
    key: 'allied-health-team-meeting-note',
    name: 'Allied Health Team Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Allied Health',
    description: 'Structured multidisciplinary allied health meeting summary.',
    prompt_instructions: 'Capture attendees, current issues, discipline updates, agreed actions, and review timing.',
    format: 'soap',
    sections: ['Attendees', 'Case Updates', 'Risks', 'Actions', 'Review Date'],
    structure: [
      section('attendees', 'Attendees', 'List the key attendees and patient context.'),
      section('case-updates', 'Case Updates', 'Summarise updates from each allied health discipline.'),
      section('risks', 'Risks / Barriers', 'Document current barriers or risk issues.'),
      section('actions', 'Actions', 'Record concrete actions, owners, and due dates.', 'plan'),
      section('review-date', 'Review Date', 'Record when the case should be reviewed next.'),
    ],
    tags: ['meeting', 'allied-health', 'team'],
    sort_order: 10,
  }),
  makeTemplate({
    key: 'board-executive-meeting-minutes',
    name: 'Board / Executive Meeting Minutes',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Administration',
    description: 'Formal executive or board minute template for clinic leadership.',
    prompt_instructions: 'Use a formal tone. Emphasise decisions, governance items, and assigned follow-up actions.',
    format: 'soap',
    sections: ['Attendees', 'Agenda Items', 'Decisions', 'Actions', 'Next Meeting'],
    structure: [
      section('attendees', 'Attendees', 'Record attendees and apologies.'),
      section('agenda-items', 'Agenda Items', 'List major topics and key discussion points.'),
      section('decisions', 'Decisions', 'Capture formal decisions or approvals.'),
      section('actions', 'Actions', 'Assign actions with owners and deadlines.', 'plan'),
      section('next-meeting', 'Next Meeting', 'Document the next scheduled meeting if discussed.'),
    ],
    tags: ['meeting', 'board', 'governance'],
    sort_order: 20,
  }),
  makeTemplate({
    key: 'business-meeting',
    name: 'Business Meeting',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Administration',
    description: 'General business meeting template for clinic operations.',
    prompt_instructions: 'Summarise agenda items, decisions made, and operational follow-up actions.',
    format: 'soap',
    sections: ['Agenda', 'Discussion', 'Decisions', 'Actions'],
    structure: [
      section('agenda', 'Agenda', 'List the meeting agenda items.'),
      section('discussion', 'Discussion', 'Summarise the material discussion for each item.'),
      section('decisions', 'Decisions', 'Record the outcomes reached.'),
      section('actions', 'Actions', 'Capture owners and due dates for next steps.', 'plan'),
    ],
    tags: ['meeting', 'operations', 'business'],
    sort_order: 30,
  }),
  makeTemplate({
    key: 'ckd-clinic-letter',
    name: 'CKD Clinic Letter',
    category: 'clinic_letter',
    output_kind: 'letter',
    specialty: 'Nephrology',
    description: 'Chronic kidney disease clinic follow-up letter template.',
    prompt_instructions: 'Write for a referring clinician. Include renal trajectory, key labs, medication changes, and follow-up plan.',
    format: 'soap',
    sections: ['Reason for Review', 'Interval History', 'Renal Function', 'Medication Changes', 'Assessment', 'Plan'],
    structure: [
      section('reason', 'Reason for Review', 'State why the patient was reviewed in CKD clinic.', 'subjective'),
      section('interval-history', 'Interval History', 'Summarise symptoms, adherence, and interval events.', 'subjective'),
      section('renal-function', 'Renal Function / Results', 'Include recent renal function, urine results, BP, and relevant trends.', 'objective'),
      section('medication-changes', 'Medication Changes', 'Highlight changes to antihypertensives, diuretics, or nephrology medications.', 'plan'),
      section('assessment', 'Assessment', 'State the renal assessment and stage/trajectory.', 'assessment'),
      section('plan', 'Plan', 'Document monitoring and follow-up plan.', 'plan'),
    ],
    tags: ['nephrology', 'ckd', 'clinic-letter'],
    sort_order: 40,
  }),
  makeTemplate({
    key: 'carers-certificate',
    name: "Carer's Certificate",
    category: 'certificate',
    output_kind: 'certificate',
    specialty: null,
    description: 'Certificate structure for carers requiring documentation.',
    prompt_instructions: 'Produce certificate-ready facts only. Avoid unsupported claims and clearly state dates and reasons.',
    format: 'soap',
    sections: ['Recipient Details', 'Clinical Basis', 'Support Period', 'Restrictions / Notes'],
    structure: [
      section('recipient', 'Recipient Details', 'Identify the carer and patient relationship.'),
      section('clinical-basis', 'Clinical Basis', 'State the clinical reason support is required.'),
      section('support-period', 'Support Period', 'Specify dates or duration of support needed.'),
      section('restrictions', 'Restrictions / Notes', 'Add any practical limitations or notes.'),
    ],
    tags: ['certificate', 'carer'],
    sort_order: 50,
  }),
  makeTemplate({
    key: 'case-review-clinical-supervision-note',
    name: 'Case Review / Clinical Supervision Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Structured case review or supervision documentation.',
    prompt_instructions: 'Capture clinical issues discussed, supervisor guidance, risk points, and agreed next steps.',
    format: 'soap',
    sections: ['Case Summary', 'Discussion', 'Risks', 'Guidance', 'Actions'],
    structure: [
      section('case-summary', 'Case Summary', 'Summarise the case under review.'),
      section('discussion', 'Discussion', 'Capture the supervisory discussion and key questions.'),
      section('risks', 'Risks', 'Document major clinical or operational risks.'),
      section('guidance', 'Guidance', 'Record recommendations or supervision advice.', 'assessment'),
      section('actions', 'Actions', 'Capture agreed next steps and responsibility.', 'plan'),
    ],
    tags: ['meeting', 'supervision', 'case-review'],
    sort_order: 60,
  }),
  makeTemplate({
    key: 'clinical-governance-meeting-note',
    name: 'Clinical Governance Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Governance',
    description: 'Clinical governance meeting structure for quality and safety oversight.',
    prompt_instructions: 'Focus on incidents, risks, quality actions, decisions, and governance follow-up.',
    format: 'soap',
    sections: ['Incidents / Metrics', 'Discussion', 'Risks', 'Decisions', 'Actions'],
    structure: [
      section('incidents-metrics', 'Incidents / Metrics', 'Capture incidents, audit findings, or safety metrics reviewed.'),
      section('discussion', 'Discussion', 'Summarise governance discussion and interpretation.'),
      section('risks', 'Risks', 'Document current risk items or escalation points.'),
      section('decisions', 'Decisions', 'Record governance decisions made.'),
      section('actions', 'Actions', 'List owners and deadlines for follow-up actions.', 'plan'),
    ],
    tags: ['meeting', 'governance', 'quality'],
    sort_order: 70,
  }),
  makeTemplate({
    key: 'departmental-team-meeting-note',
    name: 'Departmental Team Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Department team meeting template for updates and actions.',
    prompt_instructions: 'Keep the note concise and action-led. Highlight updates, blockers, and owners.',
    format: 'soap',
    sections: ['Updates', 'Discussion', 'Blockers', 'Actions'],
    structure: [
      section('updates', 'Updates', 'Summarise departmental updates shared.'),
      section('discussion', 'Discussion', 'Capture notable discussion points.'),
      section('blockers', 'Blockers', 'Document issues needing follow-up or escalation.'),
      section('actions', 'Actions', 'Assign clear next steps.', 'plan'),
    ],
    tags: ['meeting', 'department'],
    sort_order: 80,
  }),
  makeTemplate({
    key: 'discharge-planning-meeting-note',
    name: 'Discharge Planning Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Discharge planning meeting note focused on readiness and required supports.',
    prompt_instructions: 'Capture discharge barriers, supports needed, destination, and who is responsible for each task.',
    format: 'soap',
    sections: ['Current Status', 'Barriers', 'Support Needs', 'Plan', 'Owners'],
    structure: [
      section('current-status', 'Current Status', 'Summarise the patient status relevant to discharge.'),
      section('barriers', 'Barriers', 'Document outstanding barriers to discharge.'),
      section('support-needs', 'Support Needs', 'List equipment, community services, transport, or family needs.'),
      section('plan', 'Plan', 'Document the discharge plan and timing.', 'plan'),
      section('owners', 'Owners', 'Assign ownership of next steps.', 'plan'),
    ],
    tags: ['meeting', 'discharge', 'handover'],
    sort_order: 90,
  }),
  makeTemplate({
    key: 'family-meeting-case-conference-note',
    name: 'Family Meeting / Case Conference Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Family meeting or case conference documentation template.',
    prompt_instructions: 'Record attendees, goals of discussion, options discussed, decisions, and agreed follow-up.',
    format: 'soap',
    sections: ['Attendees', 'Goals', 'Discussion', 'Decisions', 'Follow-up'],
    structure: [
      section('attendees', 'Attendees', 'List attendees and roles.'),
      section('goals', 'Goals', 'Summarise the purpose of the meeting.'),
      section('discussion', 'Discussion', 'Capture key issues discussed with family or team.'),
      section('decisions', 'Decisions', 'Record decisions or points of agreement.'),
      section('follow-up', 'Follow-up', 'Document next steps, responsibilities, and timing.', 'plan'),
    ],
    tags: ['meeting', 'family', 'case-conference'],
    sort_order: 100,
  }),
  makeTemplate({
    key: 'generic-referral-letter',
    name: 'Generic Referral Letter',
    category: 'referral_letter',
    output_kind: 'letter',
    specialty: null,
    description: 'General referral letter template for external clinicians or services.',
    prompt_instructions: 'Write in a concise referral style. State reason for referral, pertinent history, relevant findings, and requested input.',
    format: 'soap',
    sections: ['Referral Reason', 'Clinical Background', 'Relevant Findings', 'Current Management', 'Requested Input'],
    structure: [
      section('referral-reason', 'Referral Reason', 'State clearly why the referral is being made.', 'subjective'),
      section('clinical-background', 'Clinical Background', 'Summarise relevant history and context.', 'subjective'),
      section('relevant-findings', 'Relevant Findings', 'Include relevant examination or results.', 'objective'),
      section('current-management', 'Current Management', 'List current management and treatments to date.', 'plan'),
      section('requested-input', 'Requested Input', 'State what opinion or management is requested.', 'assessment'),
    ],
    tags: ['letter', 'referral'],
    sort_order: 110,
  }),
  makeTemplate({
    key: 'history-and-physical',
    name: 'H & P',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'History and physical examination structure.',
    prompt_instructions: 'Organise the note as a concise history and physical while still preserving a reviewable SOAP outcome.',
    format: 'soap',
    sections: ['Presenting Complaint', 'History', 'Examination', 'Assessment', 'Plan'],
    structure: [
      section('presenting-complaint', 'Presenting Complaint', 'Summarise the presenting issue.', 'subjective'),
      section('history', 'History', 'Capture the relevant history and review items.', 'subjective'),
      section('examination', 'Examination', 'Document physical findings and objective data.', 'objective'),
      section('assessment', 'Assessment', 'State clinical impression and differentials.', 'assessment'),
      section('plan', 'Plan', 'Outline the management plan.', 'plan'),
    ],
    tags: ['clinical-note', 'history', 'examination'],
    sort_order: 120,
  }),
  makeTemplate({
    key: 'history-and-physical-including-issues',
    name: 'H & P (Including Issues)',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'History and physical note with a discrete issues list.',
    prompt_instructions: 'Include a distinct problem/issue list and tie each issue to an assessment and plan.',
    format: 'soap',
    sections: ['Presenting Complaint', 'History', 'Examination', 'Issues List', 'Assessment', 'Plan'],
    structure: [
      section('presenting-complaint', 'Presenting Complaint', 'Summarise the presenting issue.', 'subjective'),
      section('history', 'History', 'Capture relevant history and context.', 'subjective'),
      section('examination', 'Examination', 'Document objective findings.', 'objective'),
      section('issues-list', 'Issues List', 'List discrete active issues or problems.', 'assessment'),
      section('assessment', 'Assessment', 'State clinical impression for each issue.', 'assessment'),
      section('plan', 'Plan', 'Tie management steps to each issue.', 'plan'),
    ],
    tags: ['clinical-note', 'history', 'issues'],
    sort_order: 130,
  }),
  makeTemplate({
    key: 'initial-ckd-nutrition-assessment',
    name: 'Initial CKD Nutrition Assessment',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: 'Nephrology',
    description: 'Initial dietetic or nutrition review for CKD patients.',
    prompt_instructions: 'Capture renal nutrition assessment, dietary history, anthropometrics, education provided, and agreed nutrition goals.',
    format: 'soap',
    sections: ['Reason for Review', 'Dietary History', 'Nutrition Assessment', 'Education', 'Plan'],
    structure: [
      section('reason', 'Reason for Review', 'State why the CKD nutrition assessment was requested.', 'subjective'),
      section('dietary-history', 'Dietary History', 'Summarise diet, appetite, fluid intake, and relevant lifestyle factors.', 'subjective'),
      section('nutrition-assessment', 'Nutrition Assessment', 'Capture weight, trends, labs, and risk factors.', 'objective'),
      section('education', 'Education', 'Record education and counselling provided.', 'assessment'),
      section('plan', 'Plan', 'List goals, follow-up, and monitoring plan.', 'plan'),
    ],
    tags: ['nephrology', 'nutrition', 'ckd'],
    sort_order: 140,
  }),
  makeTemplate({
    key: 'issues-list',
    name: 'Issues List',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'Problem-oriented template focused on discrete issues.',
    prompt_instructions: 'Prioritise the problem list. Each issue should have a concise status update and corresponding plan.',
    format: 'soap',
    sections: ['Issues', 'Status', 'Actions'],
    structure: [
      section('issues', 'Issues', 'List the active issues in priority order.', 'assessment'),
      section('status', 'Status', 'Summarise the current status or evidence for each issue.', 'objective'),
      section('actions', 'Actions', 'State the action plan for each issue.', 'plan'),
    ],
    tags: ['clinical-note', 'problems'],
    sort_order: 150,
  }),
  makeTemplate({
    key: 'letter-to-referring-practitioner',
    name: 'Letter to Referring Practitioner',
    category: 'clinic_letter',
    output_kind: 'letter',
    specialty: null,
    description: 'Update letter addressed to the referring practitioner.',
    prompt_instructions: 'Use formal correspondence style and focus on interval events, current assessment, and the requested follow-up.',
    format: 'soap',
    sections: ['Reason for Letter', 'Interval History', 'Findings', 'Assessment', 'Plan'],
    structure: [
      section('reason', 'Reason for Letter', 'State the context for writing to the referring practitioner.', 'subjective'),
      section('interval-history', 'Interval History', 'Summarise interval events and symptoms.', 'subjective'),
      section('findings', 'Findings', 'Capture relevant examination and investigation findings.', 'objective'),
      section('assessment', 'Assessment', 'Provide the current impression.', 'assessment'),
      section('plan', 'Plan', 'Outline next steps and requests of the referring practitioner.', 'plan'),
    ],
    tags: ['letter', 'referrer'],
    sort_order: 160,
  }),
  makeTemplate({
    key: 'mdt-meeting-note',
    name: 'MDT Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Multidisciplinary team meeting note template.',
    prompt_instructions: 'Capture key specialty perspectives, the agreed consensus plan, and any unresolved items.',
    format: 'soap',
    sections: ['Case Summary', 'Discipline Input', 'Consensus', 'Actions'],
    structure: [
      section('case-summary', 'Case Summary', 'Summarise the patient or project being discussed.'),
      section('discipline-input', 'Discipline Input', 'Capture contributions from each discipline.'),
      section('consensus', 'Consensus', 'Record the agreed assessment or recommendation.', 'assessment'),
      section('actions', 'Actions', 'Assign follow-up tasks and owners.', 'plan'),
    ],
    tags: ['meeting', 'mdt'],
    sort_order: 170,
  }),
  makeTemplate({
    key: 'medical-certificate',
    name: 'Medical Certificate',
    category: 'certificate',
    output_kind: 'certificate',
    specialty: null,
    description: 'Medical certificate template with dates and capacity guidance.',
    prompt_instructions: 'Only include certifiable facts. State incapacity period, restrictions, and review timing clearly.',
    format: 'soap',
    sections: ['Condition / Reason', 'Dates Covered', 'Capacity / Restrictions', 'Review'],
    structure: [
      section('condition', 'Condition / Reason', 'State the medical basis for the certificate.'),
      section('dates-covered', 'Dates Covered', 'Specify the relevant leave or certificate period.'),
      section('capacity', 'Capacity / Restrictions', 'Document work capacity or restrictions.'),
      section('review', 'Review', 'State if review is required and when.'),
    ],
    tags: ['certificate', 'medical'],
    sort_order: 180,
  }),
  makeTemplate({
    key: 'mental-health-care-planning-meeting',
    name: 'Mental Health Care Planning Meeting',
    category: 'care_planning',
    output_kind: 'note',
    specialty: 'Mental Health',
    description: 'Meeting template for mental health care planning and review.',
    prompt_instructions: 'Document goals, risks, supports, agreed interventions, and review timing clearly.',
    format: 'soap',
    sections: ['Current Concerns', 'Risk / Protective Factors', 'Goals', 'Interventions', 'Follow-up'],
    structure: [
      section('current-concerns', 'Current Concerns', 'Summarise the main presenting concerns and context.', 'subjective'),
      section('risk-factors', 'Risk / Protective Factors', 'Document key risk and protective factors.', 'objective'),
      section('goals', 'Goals', 'List the agreed care goals.', 'assessment'),
      section('interventions', 'Interventions', 'Capture planned interventions and supports.', 'plan'),
      section('follow-up', 'Follow-up', 'Record follow-up timing and responsibilities.', 'plan'),
    ],
    tags: ['mental-health', 'care-plan'],
    sort_order: 190,
  }),
  makeTemplate({
    key: 'morbidity-and-mortality-meeting-note',
    name: 'Morbidity and Mortality (M&M) Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Governance',
    description: 'Morbidity and mortality review meeting note template.',
    prompt_instructions: 'Document case summary, contributing factors, lessons learned, and system actions.',
    format: 'soap',
    sections: ['Case Summary', 'Contributing Factors', 'Learning Points', 'Actions'],
    structure: [
      section('case-summary', 'Case Summary', 'Summarise the case or event reviewed.'),
      section('contributing-factors', 'Contributing Factors', 'Capture clinical and system factors discussed.'),
      section('learning-points', 'Learning Points', 'Record lessons or changes identified.'),
      section('actions', 'Actions', 'Assign actions and escalation points.', 'plan'),
    ],
    tags: ['meeting', 'mm', 'quality'],
    sort_order: 200,
  }),
  makeTemplate({
    key: 'nephrology-consultation',
    name: 'Nephrology Consultation',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: 'Nephrology',
    description: 'Specialty consultation template for renal review.',
    prompt_instructions: 'Focus on renal indications, baseline function, urine studies, blood pressure, medication review, and follow-up.',
    format: 'soap',
    sections: ['Referral Question', 'Renal History', 'Findings / Results', 'Impression', 'Plan'],
    structure: [
      section('referral-question', 'Referral Question', 'State the reason for nephrology consultation.', 'subjective'),
      section('renal-history', 'Renal History', 'Capture renal symptoms, past renal history, and relevant comorbidities.', 'subjective'),
      section('findings', 'Findings / Results', 'Document renal function, urine findings, imaging, BP, and exam results.', 'objective'),
      section('impression', 'Impression', 'State the nephrology impression and differential.', 'assessment'),
      section('plan', 'Plan', 'Document investigation, treatment, and follow-up plan.', 'plan'),
    ],
    tags: ['nephrology', 'consultation'],
    sort_order: 210,
  }),
  makeTemplate({
    key: 'nephrology-note',
    name: 'Nephrology Note',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: 'Nephrology',
    description: 'General nephrology progress or review note.',
    prompt_instructions: 'Keep the structure renal-specific with labs, fluid status, medication review, and renal management plan.',
    format: 'soap',
    sections: ['Interval History', 'Renal Findings', 'Assessment', 'Plan'],
    structure: [
      section('interval-history', 'Interval History', 'Summarise interval renal symptoms and clinical changes.', 'subjective'),
      section('renal-findings', 'Renal Findings', 'Capture results, fluid status, urine output, and relevant objective findings.', 'objective'),
      section('assessment', 'Assessment', 'State the renal assessment.', 'assessment'),
      section('plan', 'Plan', 'Document medication, investigation, and follow-up plan.', 'plan'),
    ],
    tags: ['nephrology', 'progress-note'],
    sort_order: 220,
  }),
  makeTemplate({
    key: 'nephrology-outpatient-clinic-letter-follow-up',
    name: 'Nephrology Outpatient Clinic Letter Follow Up',
    category: 'clinic_letter',
    output_kind: 'letter',
    specialty: 'Nephrology',
    description: 'Follow-up outpatient nephrology clinic letter.',
    prompt_instructions: 'Write a follow-up clinic letter with interval progress, key results, medication changes, and monitoring plan.',
    format: 'soap',
    sections: ['Interval Progress', 'Key Results', 'Medication Changes', 'Assessment', 'Plan'],
    structure: [
      section('interval-progress', 'Interval Progress', 'Summarise what has changed since the last review.', 'subjective'),
      section('key-results', 'Key Results', 'Include relevant recent renal results and observations.', 'objective'),
      section('medication-changes', 'Medication Changes', 'Highlight medication changes or adherence issues.', 'plan'),
      section('assessment', 'Assessment', 'State the current nephrology impression.', 'assessment'),
      section('plan', 'Plan', 'Document the follow-up and monitoring plan.', 'plan'),
    ],
    tags: ['nephrology', 'clinic-letter', 'follow-up'],
    sort_order: 230,
  }),
  makeTemplate({
    key: 'network-meeting-note',
    name: 'Network Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: null,
    description: 'Template for network or partner meetings.',
    prompt_instructions: 'Summarise updates, shared decisions, dependencies, and agreed follow-up work.',
    format: 'soap',
    sections: ['Updates', 'Discussion', 'Decisions', 'Actions'],
    structure: [
      section('updates', 'Updates', 'Capture key updates shared across the network.'),
      section('discussion', 'Discussion', 'Summarise the main discussion themes.'),
      section('decisions', 'Decisions', 'Record any agreements or decisions reached.'),
      section('actions', 'Actions', 'Assign next steps and owners.', 'plan'),
    ],
    tags: ['meeting', 'network'],
    sort_order: 240,
  }),
  makeTemplate({
    key: 'patient-explainer-letter',
    name: 'Patient Explainer Letter',
    category: 'patient_communication',
    output_kind: 'patient_summary',
    specialty: null,
    description: 'Plain-language patient explainer template.',
    prompt_instructions: 'Write clearly for the patient. Explain what was discussed, medication changes, next steps, and when to seek urgent help.',
    format: 'visit_summary',
    sections: ['What We Discussed', 'What Changed', 'Next Steps', 'When to Get Help'],
    structure: [
      section('what-we-discussed', 'What We Discussed', 'Explain the main consultation topics in plain language.'),
      section('what-changed', 'What Changed', 'Summarise treatment or medication changes simply.'),
      section('next-steps', 'Next Steps', 'List the next actions for the patient and clinic.', 'plan'),
      section('when-to-get-help', 'When to Get Help', 'Explain warning symptoms or reasons to seek urgent review.'),
    ],
    tags: ['patient', 'summary', 'plain-language'],
    sort_order: 250,
  }),
  makeTemplate({
    key: 'patient-family-follow-up-email',
    name: 'Patient & Family Follow-up Email',
    category: 'patient_communication',
    output_kind: 'patient_summary',
    specialty: null,
    description: 'Email-ready follow-up update written for patients, families, and carers.',
    prompt_instructions:
      'Write as a warm, plain-language clinical follow-up email for the patient and their family or carers. Summarise what was discussed, medication changes, next steps, and when to seek urgent help.',
    format: 'visit_summary',
    sections: [
      'Greeting',
      'What We Discussed',
      'Medication Changes',
      'Next Steps',
      'When To Get Help',
      'Family / Carer Notes',
    ],
    structure: [
      section('greeting', 'Greeting', 'Open with a patient- and family-appropriate greeting.'),
      section('what-we-discussed', 'What We Discussed', 'Summarise the consult in plain language.'),
      section('medication-changes', 'Medication Changes', 'Explain medicine changes simply and clearly.'),
      section('next-steps', 'Next Steps', 'List the next actions for the patient, family, and clinic.', 'plan'),
      section('when-to-get-help', 'When To Get Help', 'State red flags and urgent care advice in plain language.'),
      section('family-carer-notes', 'Family / Carer Notes', 'Include any instructions that help family or carers support the patient.'),
    ],
    tags: ['patient', 'family', 'carer', 'email', 'plain-language'],
    sort_order: 255,
  }),
  makeTemplate({
    key: 'paediatric-nephrology-clinic',
    name: 'Pediatric Nephrology Clinic',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: 'Paediatric Nephrology',
    description: 'Paediatric nephrology clinic review template.',
    prompt_instructions: 'Include caregiver history, growth concerns, renal findings, development/context, and family instructions.',
    format: 'soap',
    sections: ['Parent / Carer Concerns', 'Interval History', 'Growth / Renal Findings', 'Assessment', 'Plan'],
    structure: [
      section('carer-concerns', 'Parent / Carer Concerns', 'Capture parent or carer concerns and symptoms.', 'subjective'),
      section('interval-history', 'Interval History', 'Summarise interval symptoms, admissions, or treatment changes.', 'subjective'),
      section('growth-renal-findings', 'Growth / Renal Findings', 'Document growth, BP, urine findings, labs, and examination.', 'objective'),
      section('assessment', 'Assessment', 'State the paediatric renal assessment.', 'assessment'),
      section('plan', 'Plan', 'Document investigation, treatment, and family follow-up plan.', 'plan'),
    ],
    tags: ['paediatric', 'nephrology'],
    sort_order: 260,
  }),
  makeTemplate({
    key: 'practice-clinic-management-meeting-note',
    name: 'Practice / Clinic Management Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Administration',
    description: 'Management meeting template for clinic operations.',
    prompt_instructions: 'Focus on operational issues, decisions, staffing, finance, and action owners.',
    format: 'soap',
    sections: ['Operational Updates', 'Issues', 'Decisions', 'Actions'],
    structure: [
      section('operational-updates', 'Operational Updates', 'Capture core operational updates reviewed.'),
      section('issues', 'Issues', 'List issues or blockers requiring discussion.'),
      section('decisions', 'Decisions', 'Record management decisions made.'),
      section('actions', 'Actions', 'Assign owners and timelines.', 'plan'),
    ],
    tags: ['meeting', 'management', 'practice'],
    sort_order: 270,
  }),
  makeTemplate({
    key: 'quality-improvement-project-meeting-note',
    name: 'Quality Improvement Project Meeting Note',
    category: 'meeting_note',
    output_kind: 'meeting',
    specialty: 'Quality Improvement',
    description: 'QI project meeting template for project status and actions.',
    prompt_instructions: 'Record aims, data reviewed, change ideas, decisions, and next test cycles.',
    format: 'soap',
    sections: ['Aim / Scope', 'Data Reviewed', 'Insights', 'Actions', 'Next Review'],
    structure: [
      section('aim-scope', 'Aim / Scope', 'State the project aim and scope discussed.'),
      section('data-reviewed', 'Data Reviewed', 'Summarise measures or data reviewed.'),
      section('insights', 'Insights', 'Record learning points or change ideas.'),
      section('actions', 'Actions', 'List owners and deadlines for next steps.', 'plan'),
      section('next-review', 'Next Review', 'Note next review timing or PDSA cycle.'),
    ],
    tags: ['meeting', 'quality-improvement'],
    sort_order: 280,
  }),
  makeTemplate({
    key: 'referral-letter',
    name: 'Referral Letter',
    category: 'referral_letter',
    output_kind: 'letter',
    specialty: null,
    description: 'Referral letter template with more formal correspondence structure.',
    prompt_instructions: 'Generate a concise clinician-facing referral letter with clear reason, background, relevant findings, and requested review.',
    format: 'soap',
    sections: ['Reason for Referral', 'Background', 'Findings', 'Current Management', 'Request'],
    structure: [
      section('reason-for-referral', 'Reason for Referral', 'State the referral question clearly.', 'subjective'),
      section('background', 'Background', 'Provide the relevant clinical background.', 'subjective'),
      section('findings', 'Findings', 'Document pertinent examination or investigation findings.', 'objective'),
      section('current-management', 'Current Management', 'List what has been done so far.', 'plan'),
      section('request', 'Request', 'State what specialist input is requested.', 'assessment'),
    ],
    tags: ['letter', 'referral'],
    sort_order: 290,
  }),
  makeTemplate({
    key: 'renal-review-note',
    name: 'Renal Review Note',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: 'Nephrology',
    description: 'Focused renal review note template.',
    prompt_instructions: 'Prioritise renal status, trends, medication review, and next monitoring actions.',
    format: 'soap',
    sections: ['Interval Symptoms', 'Renal Metrics', 'Assessment', 'Plan'],
    structure: [
      section('interval-symptoms', 'Interval Symptoms', 'Capture interval symptoms and changes.', 'subjective'),
      section('renal-metrics', 'Renal Metrics', 'Document labs, urine findings, BP, fluid status, and examination.', 'objective'),
      section('assessment', 'Assessment', 'State the renal assessment.', 'assessment'),
      section('plan', 'Plan', 'Outline monitoring, treatment, and follow-up.', 'plan'),
    ],
    tags: ['nephrology', 'review-note'],
    sort_order: 300,
  }),
  makeTemplate({
    key: 'smart-goals',
    name: 'SMART Goals',
    category: 'care_planning',
    output_kind: 'goals',
    specialty: null,
    description: 'Goal-setting template using SMART framing.',
    prompt_instructions: 'Convert the plan into specific, measurable, achievable, relevant, and time-bound goals with responsibilities.',
    format: 'visit_summary',
    sections: ['Goals', 'Measures', 'Timeline', 'Supports / Barriers'],
    structure: [
      section('goals', 'Goals', 'State each goal clearly and specifically.', 'assessment'),
      section('measures', 'Measures', 'Describe how progress will be measured.'),
      section('timeline', 'Timeline', 'State timeframes and review points.', 'plan'),
      section('supports-barriers', 'Supports / Barriers', 'List supports and anticipated barriers.'),
    ],
    tags: ['goals', 'care-plan'],
    sort_order: 310,
  }),
  makeTemplate({
    key: 'soap-note',
    name: 'SOAP Note',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'Standard subjective, objective, assessment, plan note.',
    prompt_instructions: 'Generate a standard concise SOAP note suitable for clinical review.',
    format: 'soap',
    sections: ['Subjective', 'Objective', 'Assessment', 'Plan'],
    structure: [
      section('subjective', 'Subjective', 'Patient-reported symptoms, history, and concerns.', 'subjective'),
      section('objective', 'Objective', 'Clinical findings, observed data, and results.', 'objective'),
      section('assessment', 'Assessment', 'Clinical impression, interpretation, and differential.', 'assessment'),
      section('plan', 'Plan', 'Management, medications, referrals, and follow-up.', 'plan'),
    ],
    tags: ['clinical-note', 'soap'],
    sort_order: 320,
    is_default: true,
  }),
  makeTemplate({
    key: 'soap-note-including-issues',
    name: 'SOAP Note (Including Issues)',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'SOAP note with an explicit problem or issues list.',
    prompt_instructions: 'Generate a SOAP note and include a discrete issues list to improve reviewability.',
    format: 'soap',
    sections: ['Subjective', 'Objective', 'Issues', 'Assessment', 'Plan'],
    structure: [
      section('subjective', 'Subjective', 'Patient-reported symptoms, history, and concerns.', 'subjective'),
      section('objective', 'Objective', 'Clinical findings, observed data, and results.', 'objective'),
      section('issues', 'Issues', 'List the active problems or issues explicitly.', 'assessment'),
      section('assessment', 'Assessment', 'Clinical impression and interpretation.', 'assessment'),
      section('plan', 'Plan', 'Management and follow-up linked to the issues listed.', 'plan'),
    ],
    tags: ['clinical-note', 'soap', 'issues'],
    sort_order: 330,
  }),
  makeTemplate({
    key: 'ward-round-clinical-handover-note',
    name: 'Ward Round / Clinical Handover Note',
    category: 'clinical_note',
    output_kind: 'note',
    specialty: null,
    description: 'Ward round or handover summary template.',
    prompt_instructions: 'Keep the note concise and handover-friendly. Emphasise overnight events, current issues, escalation points, and tasks.',
    format: 'progress',
    sections: ['Overnight Events', 'Current Status', 'Issues / Risks', 'Plan / Handover'],
    structure: [
      section('overnight-events', 'Overnight Events', 'Summarise overnight events or interval changes.', 'subjective'),
      section('current-status', 'Current Status', 'Document current objective status and key findings.', 'objective'),
      section('issues-risks', 'Issues / Risks', 'List active issues, risks, or watch-points.', 'assessment'),
      section('plan-handover', 'Plan / Handover', 'Capture tasks, escalation thresholds, and handover points.', 'plan'),
    ],
    tags: ['handover', 'ward-round'],
    sort_order: 340,
  }),
  makeTemplate({
    key: 'work-cover-form',
    name: 'Work Cover Form',
    category: 'form',
    output_kind: 'form',
    specialty: null,
    description: 'Work cover documentation structure.',
    prompt_instructions: 'Capture work-related injury facts, capacity, restrictions, treatment, and review timing clearly.',
    format: 'soap',
    sections: ['Injury Details', 'Symptoms / Findings', 'Capacity', 'Treatment', 'Review'],
    structure: [
      section('injury-details', 'Injury Details', 'Document mechanism, date, and work context.'),
      section('symptoms-findings', 'Symptoms / Findings', 'Summarise symptoms and objective findings.', 'objective'),
      section('capacity', 'Capacity', 'State work capacity and restrictions clearly.'),
      section('treatment', 'Treatment', 'Document treatment and rehabilitation plan.', 'plan'),
      section('review', 'Review', 'Specify review timing and required follow-up.', 'plan'),
    ],
    tags: ['form', 'occupational-health'],
    sort_order: 350,
  }),
];

export function getTemplateByKey(key?: string | null) {
  if (!key) return TEMPLATE_CATALOG.find((template) => template.key === DEFAULT_TEMPLATE_KEY) ?? TEMPLATE_CATALOG[0];
  return TEMPLATE_CATALOG.find((template) => template.key === key)
    ?? TEMPLATE_CATALOG.find((template) => template.key === DEFAULT_TEMPLATE_KEY)
    ?? TEMPLATE_CATALOG[0];
}

export function searchTemplates(query: string) {
  const normalizedQuery = query.trim().toLowerCase();
  if (!normalizedQuery) return TEMPLATE_CATALOG;

  return TEMPLATE_CATALOG.filter((template) => {
    const haystack = [
      template.name,
      template.description,
      template.specialty ?? '',
      template.category,
      template.tags.join(' '),
    ].join(' ').toLowerCase();

    return haystack.includes(normalizedQuery);
  });
}
